query($limit: Int, $offset: Int) {
  posts(limit: $limit, offset: $offset) {
    posts {
      title
      dateCreated
      tags
      author
      id
      coverImage
      description
    }
    totalCount
  }
}
